Repository mendix/widgets-resources, pull requests merged in 2021-05, with the labels that each got.

#597 [WC-381] Widget generator: fix NPM v7.x.x peer dependency install issue (backport)
  packages/tools/generator-widget/README.md
  packages/tools/generator-widget/generators/app/index.js
  packages/tools/generator-widget/generators/app/templates/commons/README.md.ejs
  packages/tools/generator-widget/generators/app/templates/packages/package_native.json.ejs
  packages/tools/generator-widget/generators/app/templates/packages/package_web.json.ejs
  packages/tools/generator-widget/package.json
  packages/tools/pluggable-widgets-tools/README.md
  packages/tools/pluggable-widgets-tools/package.json
Labels: Cross-Platform, bug

#609 Fix NPM publish workflow
  .github/workflows/PublishNpm.yml
Labels: Cross-Platform, bug

#614 Align GH Actions with MX8.x branch
  .github/workflows/ScriptTests.yml
  .github/workflows/UnitTests.yml
  .github/workflows/WebAutomatedTests.yml
Labels: Cross-Platform, bug

#618 feat(pluggable-widgets-tools): suppress unused Platform warnings with both single and double quotes
  packages/tools/pluggable-widgets-tools/configs/rollup.config.js
Labels: Cross-Platform, bug

#620 Adding changelog to rating-web
  packages/pluggableWidgets/rating-web/CHANGELOG.md
Labels: Web, bug

#607 [WC-438] overwrite -webkit-overflow-scrolling in mxui with auto
  packages/pluggableWidgets/barcode-scanner-web/src/ui/BarcodeScanner.scss
Labels: Web, bug, enhancement

#622 [WC-474] Get rid of studio pro errors console.warned by @zxing/library
  packages/pluggableWidgets/barcode-scanner-web/package.json
  packages/pluggableWidgets/barcode-scanner-web/rollup.config.js
  packages/pluggableWidgets/barcode-scanner-web/src/hooks/useCodeScanner.tsx
Labels: Web, enhancement

#624 fix(calendar-web): fixing calendar drop events between different widgets
  packages/customWidgets/calendar-web/package.json
  packages/customWidgets/calendar-web/src/components/CalendarContainer.ts
  packages/customWidgets/calendar-web/src/package.xml
Labels: Web, bug

#625 feat: add mendix-version.json
  .github/workflows/ScriptTests.yml
  .github/workflows/UnitTests.yml
  .github/workflows/WebAutomatedTests.yml
  configs/e2e/mendix-versions.json
Labels: Cross-Platform, enhancement

#623 Introduce Runtime docker image
  packages/tools/pluggable-widgets-tools/scripts/e2e.js
  packages/tools/pluggable-widgets-tools/scripts/m2ee.yml
  packages/tools/pluggable-widgets-tools/scripts/runtime.Dockerfile
  packages/tools/pluggable-widgets-tools/scripts/runtime.sh
Labels: Cross-Platform, enhancement

#627 fix: glob patterns in GH actions
  .github/workflows/ScriptTests.yml
  .github/workflows/UnitTests.yml
  .github/workflows/WebAutomatedTests.yml
Labels: Cross-Platform, bug

#629 fix(pluggable-widgets-tools): fix mxbuild version in docker image
  packages/tools/pluggable-widgets-tools/scripts/mxbuild.Dockerfile
Labels: Cross-Platform, bug

#633 [WC-467] Remove github issues link in generator and package.json from widget-generator
  packages/tools/generator-widget/CHANGELOG.md
  packages/tools/generator-widget/generators/app/lib/text.js
  packages/tools/generator-widget/package.json
Labels: Cross-Platform, enhancement

#631 [WC-499] Process barcode scanner feedback
  packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.editorConfig.ts
  packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.tsx
  packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.xml
  packages/pluggableWidgets/barcode-scanner-web/src/assets/ic24-close.svg
  packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx
  packages/pluggableWidgets/barcode-scanner-web/src/components/__tests__/BarcodeScanner.spec.tsx
  packages/pluggableWidgets/barcode-scanner-web/src/components/__tests__/__snapshots__/BarcodeScanner.spec.tsx.snap
  packages/pluggableWidgets/barcode-scanner-web/src/ui/BarcodeScanner.scss
  packages/pluggableWidgets/barcode-scanner-web/typings/BarcodeScannerProps.d.ts
Labels: Web, enhancement

#605 [WC-231] PWA Take picture JS action
  configs/jsactions/rollup.config.js
  packages/jsActions/nanoflow-commons/package.json
  packages/jsActions/native-mobile-resources/package.json
  packages/jsActions/web-nanoflow-actions/package.json
  packages/jsActions/web-nanoflow-actions/src/FocusNext.ts
  packages/jsActions/web-nanoflow-actions/src/FocusPrevious.ts
  packages/jsActions/web-nanoflow-actions/src/ScrollTo.ts
  packages/jsActions/web-nanoflow-actions/src/SetFocus.ts
  packages/jsActions/web-nanoflow-actions/src/TakePicture.ts
  packages/jsActions/web-nanoflow-actions/src/tsconfig.json
Labels: Web, enhancement

#636 fix(pluggable-widgets-tools): fixing replacement of variables
  package-lock.json
  packages/tools/pluggable-widgets-tools/CHANGELOG.md
  packages/tools/pluggable-widgets-tools/configs/rollup.config.js
  packages/tools/pluggable-widgets-tools/package.json
Labels: Cross-Platform, bug

#638 feat: update mendix version
  configs/e2e/mendix-versions.json
Labels: Cross-Platform, enhancement

#635 [WC-517] Add widget properties to control barcode scanner dimensions
  packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md
  packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.editorPreview.tsx
  packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.tsx
  packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.xml
  packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx
  packages/pluggableWidgets/barcode-scanner-web/src/components/__tests__/BarcodeScanner.spec.tsx
  packages/pluggableWidgets/barcode-scanner-web/src/components/__tests__/__snapshots__/BarcodeScanner.spec.tsx.snap
  packages/pluggableWidgets/barcode-scanner-web/src/ui/BarcodeScanner.scss
  packages/pluggableWidgets/barcode-scanner-web/src/ui/BarcodeScannerPreview.scss
  packages/pluggableWidgets/barcode-scanner-web/typings/BarcodeScannerProps.d.ts
  packages/pluggableWidgets/maps-web/src/components/GoogleMap.tsx
  packages/pluggableWidgets/maps-web/src/components/LeafletMap.tsx
  packages/pluggableWidgets/maps-web/typings/shared.d.ts
  packages/tools/piw-utils-internal/src/utils/StylingPropertyUtils.ts
  packages/tools/piw-utils-internal/src/utils/index.ts
Labels: Web, enhancement

#639 chore(generator-widget): update CHANGELOG with 9.0.2 and 9.1.0
  packages/tools/generator-widget/CHANGELOG.md
Labels: Cross-Platform, documentation

#637 fix(pluggable-widgets-tools): fix commonjs imports
  packages/tools/pluggable-widgets-tools/CHANGELOG.md
  packages/tools/pluggable-widgets-tools/configs/rollup.config.js
Labels: Native, bug
